spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database:
      authentication-database: admin
      username:
      password:

management.endpoints.web.exposure.include: '*'

server:
  port: 8081