spring:
  data:
    mongodb:
      host: localhost #for now I kept localhost
      port: 27017
      database: reg
      authentication-database: admin
      username: admin
      password: admin

management.endpoints.web.exposure.include: '*'

server:
  port: 8081